In [88]:
import pandas as pd
import numpy as np

In [89]:
data = pd.read_csv("../data/karakalpak-audio-dataset-hf/cleaned/data.csv")

In [90]:
data.head()

,audio_index,filename,source_filename,sentence_latin,sentence_cyrillic,duration,snr_original,snr_16k,word_count
0,0,audio_000000.wav,kaa_audio_1000002.wav,Oktyabr ayınıń sońǵı kúnleri.,Октябрь айының соңғы күнлери.,2.967375,36.379130,36.360237,4
1,1,audio_000001.wav,kaa_audio_1000003.wav,"Kún uyasına sıymay dolanıp, qıp-qızıl shoqtay ...","Күн уясына сыймай доланып, қып-қызыл шоқтай жа...",6.952250,25.503586,25.477509,11
2,2,audio_000002.wav,kaa_audio_1000004.wav,“Kese etek”ten Qońıratqa qaray sozılǵan úlken ...,“Кесе етек”тен Қоңыратқа қарай созылған үлкен ...,5.058687,27.380424,27.334051,8
3,3,audio_000003.wav,kaa_audio_1000005.wav,Jeter jerde el joq.,Жетер жерде ел жоқ.,2.006562,30.901669,30.942450,4
4,4,audio_000004.wav,kaa_audio_1000006.wav,"Joldıń eki boyı qula dúz, keń dala (qula dúz -...","Жолдың еки бойы қула дүз, кең дала (қула дүз -...",9.693500,28.682690,28.682480,18

In [91]:
unique = []

for i in range(len(data["sentence_latin"])):
    for text in data["sentence_latin"][i].split():
        for j in text:
            if j not in unique and j.isalpha():
                unique.append(j)
print(len(unique))
print(unique)

62
['O', 'k', 't', 'y', 'a', 'b', 'r', 'ı', 'n', 'ń', 's', 'o', 'ǵ', 'ú', 'l', 'e', 'i', 'K', 'u', 'm', 'd', 'p', 'q', 'z', 'h', 'j', 'w', 'Q', 'g', 'J', 'ó', 'H', 'á', 'A', 'S', 'B', 'E', 'T', 'Á', 'U', 'N', 'Ó', 'G', 'M', 'D', 'I', 'Ú', 'W', 'Z', 'P', 'x', 'X', 'Ǵ', 'F', 'c', 'L', 'V', 'f', 'v', 'Y', 'R', 'Í']

In [92]:
original_alphabet_latin = ['A', 'a','Á', 'á','B', 'b','D', 'd','E', 'e','F', 'f','G', 'g','Ǵ', 'ǵ','H', 'h',
                          'X', 'x','Í', 'ı','I', 'i','J', 'j','K', 'k','Q', 'q','L', 'l','M', 'm','N', 'n',
                          'Ń', 'ń','O', 'o','Ó', 'ó','P', 'p','R', 'r','S', 's','T', 't','U', 'u','Ú', 'ú',
                          'V', 'v','W', 'w','Y', 'y','Z', 'z','Sh', 'sh','C', 'c','Ch', 'ch']

print(len(original_alphabet_latin))

68

In [93]:
xatolar = []

for i in unique:
    if i not in original_alphabet_latin:
        xatolar.append(i)

print(xatolar)

[]

In [94]:
text = data["sentence_latin"]
text.head()
sonli_textlar=[]
count=0
for x in range(len(data["sentence_latin"])):
    for i in data["sentence_latin"][x].split():
        for sonmi in i:
            if sonmi.isdigit():
                count+=1
print(count)

0

In [95]:
data["sentence_latin"][4]

'Joldıń eki boyı qula dúz, keń dala (qula dúz - adam jasamaytuǵın orın), appaq kebiri shıǵıp kópship atır.'

In [96]:
data_copy = data.copy()

In [97]:
data_copy.head()

,audio_index,filename,source_filename,sentence_latin,sentence_cyrillic,duration,snr_original,snr_16k,word_count
0,0,audio_000000.wav,kaa_audio_1000002.wav,Oktyabr ayınıń sońǵı kúnleri.,Октябрь айының соңғы күнлери.,2.967375,36.379130,36.360237,4
1,1,audio_000001.wav,kaa_audio_1000003.wav,"Kún uyasına sıymay dolanıp, qıp-qızıl shoqtay ...","Күн уясына сыймай доланып, қып-қызыл шоқтай жа...",6.952250,25.503586,25.477509,11
2,2,audio_000002.wav,kaa_audio_1000004.wav,“Kese etek”ten Qońıratqa qaray sozılǵan úlken ...,“Кесе етек”тен Қоңыратқа қарай созылған үлкен ...,5.058687,27.380424,27.334051,8
3,3,audio_000003.wav,kaa_audio_1000005.wav,Jeter jerde el joq.,Жетер жерде ел жоқ.,2.006562,30.901669,30.942450,4
4,4,audio_000004.wav,kaa_audio_1000006.wav,"Joldıń eki boyı qula dúz, keń dala (qula dúz -...","Жолдың еки бойы қула дүз, кең дала (қула дүз -...",9.693500,28.682690,28.682480,18

In [100]:
abbr_rows = data[
    data["sentence_latin"].str.contains(
        r"\b[A-ZÁǴÍŃÓÚ]{2,}\b|(?:[A-ZÁǴÍŃÓÚ]\.){2,}",
        regex=True,
        na=False
    )
].copy()

In [101]:
abbr_rows.head(10)

Empty DataFrame
Columns: [audio_index, filename, source_filename, sentence_latin, sentence_cyrillic, duration, snr_original, snr_16k, word_count]
Index: []

In [102]:
import re
import unicodedata

ALPHABET = (
    "AÁBDEFGǴHXÍIJKQLMNŃOÓPRSTUÚVWYZC"
    "aábdefgǵhxıijkqlmnńoóprstuúvwyzc"
)

def clean_sentence(text):
    text = unicodedata.normalize("NFC", str(text))

    # Remove punctuation but keep Karakalpak letters, digits, and spaces
    text = re.sub(
        rf"[^{re.escape(ALPHABET)}0-9\s]",
        " ",
        text
    )

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text


data["sentence_latin"] = data["sentence_latin"].apply(clean_sentence)

In [103]:
data.head()

,audio_index,filename,source_filename,sentence_latin,sentence_cyrillic,duration,snr_original,snr_16k,word_count
0,0,audio_000000.wav,kaa_audio_1000002.wav,Oktyabr ayınıń sońǵı kúnleri,Октябрь айының соңғы күнлери.,2.967375,36.379130,36.360237,4
1,1,audio_000001.wav,kaa_audio_1000003.wav,Kún uyasına sıymay dolanıp qıp qızıl shoqtay j...,"Күн уясына сыймай доланып, қып-қызыл шоқтай жа...",6.952250,25.503586,25.477509,11
2,2,audio_000002.wav,kaa_audio_1000004.wav,Kese etek ten Qońıratqa qaray sozılǵan úlken g...,“Кесе етек”тен Қоңыратқа қарай созылған үлкен ...,5.058687,27.380424,27.334051,8
3,3,audio_000003.wav,kaa_audio_1000005.wav,Jeter jerde el joq,Жетер жерде ел жоқ.,2.006562,30.901669,30.942450,4
4,4,audio_000004.wav,kaa_audio_1000006.wav,Joldıń eki boyı qula dúz keń dala qula dúz ada...,"Жолдың еки бойы қула дүз, кең дала (қула дүз -...",9.693500,28.682690,28.682480,18

In [104]:
def to_lowercase(text):
    return str(text).lower()

data["sentence_latin"] = data["sentence_latin"].apply(to_lowercase)

In [105]:
data.to_csv("../data/karakalpak-audio-dataset-hf/cleaned/removed_annotations.csv")

In [106]:
data.head()

,audio_index,filename,source_filename,sentence_latin,sentence_cyrillic,duration,snr_original,snr_16k,word_count
0,0,audio_000000.wav,kaa_audio_1000002.wav,oktyabr ayınıń sońǵı kúnleri,Октябрь айының соңғы күнлери.,2.967375,36.379130,36.360237,4
1,1,audio_000001.wav,kaa_audio_1000003.wav,kún uyasına sıymay dolanıp qıp qızıl shoqtay j...,"Күн уясына сыймай доланып, қып-қызыл шоқтай жа...",6.952250,25.503586,25.477509,11
2,2,audio_000002.wav,kaa_audio_1000004.wav,kese etek ten qońıratqa qaray sozılǵan úlken g...,“Кесе етек”тен Қоңыратқа қарай созылған үлкен ...,5.058687,27.380424,27.334051,8
3,3,audio_000003.wav,kaa_audio_1000005.wav,jeter jerde el joq,Жетер жерде ел жоқ.,2.006562,30.901669,30.942450,4
4,4,audio_000004.wav,kaa_audio_1000006.wav,joldıń eki boyı qula dúz keń dala qula dúz ada...,"Жолдың еки бойы қула дүз, кең дала (қула дүз -...",9.693500,28.682690,28.682480,18